
##
# RLStevenson Theme Options
####

# For baseurl:
# Use '' for / or '/your-dir' for another directory

title:		Fang's Blog
description:	'Remote sensing, GIS, Hazard analysis '
freetext:	'None'
baseurl:	'https://zhang2408.github.io/Fangblog.github.io/'
paginate:	3
version:	1.0.0
colorscheme:	scheme-gulfracing

ga:		'UA-123-456'
piwikSiteID:	''
piwikURL:	''

markdown: kramdown
highlighter: rouge
excerpt_separator: "<!-- more -->"


author:
 url:		https://www.exchangerate-api.com
 name:		'ExchangeRate-API'

github:
 repo:		https://github.com/ExchangeRate-API/rlstevenson-jekyll-theme

gems:		[jekyll-paginate]

exclude:	['README.md', 'Gemfile.lock', 'Gemfile', '*.gemspec', '*.gem']
